language: python
python:
  - "2.7"           # this works for Linux but is ignored on macOS or Windows
  - "3.8"
  - "nightly"
  # PyPy versions
  - "pypy"   # currently Python 2.7.13, PyPy 7.1.1
  - "pypy3"  # currently Python 3.6.1,  PyPy 7.1.1-beta0
services:
  - xvfb
before_install:
  - "sleep 5"
  - "export DISPLAY=:99.0"
  - "sudo apt-get install gnuplot-x11"
  - "sudo apt-get install evince"
install:
  - pip3 install . || pip install .
  - pip3 install --upgrade pip || pip install --upgrade pip # all three OSes agree about 'pip3'
  - pip3 install nose coverage || pip install nose coverage
  # - env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
  # - pip install pypiview
  # - pip install coveralls
script:
  - python example.py
  - sleep 10
  - python setup.py nosetests --cover-package pypiview  # --with-coverage
  - ls
  - evince example.pdf
    #after_sucess:
    #coveralls
