language: python
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 
      - "3.8"           # this works for Linux but is ignored on macOS or Windows
      - "2.7"           # this works for Linux but is ignored on macOS or Windows
      - "nightly"
      - "pypy"  # PyPy2 2.5.0
      - "pypy3" # Pypy3 2.4.0
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.7.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
services:
  - xvfb
before_install:
  - "export DISPLAY=:99.0"
  - "sudo apt-get install gnuplot-x11"
install:
  # - pip install .
  - pip3 install --upgrade pip || pip install --upgrade pip # all three OSes agree about 'pip3'
  - pip3 install --user nose coverage || pip install --user nose coverage
  - env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
  # - pip install pypiview
  # - pip install coveralls
script:
  - python example.py
  - python setup.py nosetests --cover-package pypiview  # --with-coverage

    #after_sucess:
    #coveralls
