language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.8"
  # PyPy versions
  - "pypy"  # PyPy2 2.5.0
  - "pypy3" # Pypy3 2.4.0
services:
  - xvfb
before_install:
  - "export DISPLAY=:99.0"
  - "sudo apt-get install gnuplot-x11"
install:
  # - pip install .
  - pip install nose coverage
  - pip install pypiview
  # - pip install coveralls
# command to run tests
script:
  - python example.py
  - python setup.py nosetests --cover-package pypiview  # --with-coverage

    #after_sucess:
    #coveralls
